from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import typer
import yaml
from rich.console import Console

from shugo import discovery


READ_GLOBS = ["read_*", "list_*", "get_*", "search_*"]


def _starter_yaml(servers: list[dict[str, Any]]) -> str:
    upstreams: dict[str, dict[str, Any]] = {}
    rules: list[dict[str, Any]] = []

    for s in servers:
        upstreams[s["name"]] = {
            "command": s["command"],
            "args": s["args"],
            "env": s["env"],
        }
        rules.append(
            {
                "id": f"read-only-{s['name']}",
                "description": f"Read-only tools on {s['name']} are auto-allowed.",
                "match": {"server": s["name"], "tool": READ_GLOBS},
                "decision": "allow",
            }
        )
        rules.append(
            {
                "id": f"write-needs-approval-{s['name']}",
                "description": f"Any other tool on {s['name']} requires human approval.",
                "match": {"server": s["name"], "tool": "*"},
                "decision": "escalate",
                "approval": {"channel": "cli", "timeout_seconds": 300, "on_timeout": "deny"},
            }
        )

    doc = {
        "version": "0.1",
        "defaults": {"decision": "deny", "on_error": "deny"},
        "upstreams": upstreams,
        "rules": rules,
    }
    header = (
        "# SHUGO guardrails — generated by `shugo init`.\n"
        "# Edit this file to tune what your agent can and cannot do.\n"
        "# Rules match top-to-bottom; first match wins; unmatched calls are denied.\n"
        "\n"
    )
    return header + yaml.safe_dump(doc, sort_keys=False)


def _print_client_snippet(console: Console, out_path: Path) -> None:
    snippet = {
        "mcpServers": {
            "shugo": {
                "command": "uvx",
                "args": ["shugo", "serve", "--config", str(out_path.resolve())],
            }
        }
    }
    console.print()
    console.print("[bold]Point your MCP client at SHUGO by replacing your mcpServers block with:[/bold]")
    console.print()
    console.print(json.dumps(snippet, indent=2))
    console.print()


def run(
    from_: Path | None,
    out: Path,
    console: Console,
    enumerate_upstreams: bool = True,
) -> int:
    path = from_ or discovery.find_client_config()
    if path is None:
        console.print("[red]no MCP client config found[/red]")
        console.print(
            "  looked in: " + ", ".join(str(p) for p in discovery.default_client_config_paths())
        )
        console.print("  re-run with --from PATH to point at your config")
        raise typer.Exit(code=1)

    try:
        servers = discovery.parse_client_config(path)
    except (OSError, json.JSONDecodeError) as e:
        console.print(f"[red]cannot read {path}: {e}[/red]")
        raise typer.Exit(code=1)

    if not servers:
        console.print(f"[yellow]no upstream MCP servers found in {path}[/yellow]")
        raise typer.Exit(code=1)

    console.print(f"[dim]found client config[/dim] {path}")
    for s in servers:
        console.print(f"  - {s.name} ({s.command} {' '.join(s.args)})")

    if enumerate_upstreams:
        for s in servers:
            tools = discovery.enumerate_tools(s)
            if tools is None:
                console.print(
                    f"  [yellow]could not enumerate tools for {s.name} — writing spec anyway[/yellow]"
                )
            else:
                console.print(f"  [green]{s.name}[/green]: {len(tools)} tools discovered")

    body = _starter_yaml(
        [
            {"name": s.name, "command": s.command, "args": s.args, "env": s.env}
            for s in servers
        ]
    )

    if out.exists():
        backup = out.with_suffix(out.suffix + ".shugo-backup")
        shutil.copy2(out, backup)
        console.print(f"[dim]backed up existing {out} -> {backup}[/dim]")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    console.print(f"[green]wrote[/green] {out}")

    _print_client_snippet(console, out)
    return 0
